#ntrospeccionModules.py
from tkinter import *
import tkinter
t="tkinter."
x=dir(tkinter)
print(x)
for i in x:
	g=t+i 
	print(g)

def tkArgs():
	tkinter.ACTIVE
	tkinter.ALL
	tkinter.ANCHOR
	tkinter.ARC
	tkinter.BASELINE
	tkinter.BEVEL
	tkinter.BOTH
	tkinter.BOTTOM
	tkinter.BROWSE
	tkinter.BUTT
	tkinter.BaseWidget
	tkinter.BitmapImage
	tkinter.BooleanVar
	tkinter.Button
	tkinter.CASCADE
	tkinter.CENTER
	tkinter.CHAR
	tkinter.CHECKBUTTON
	tkinter.CHORD
	tkinter.COMMAND
	tkinter.CURRENT
	tkinter.CallWrapper
	tkinter.Canvas
	tkinter.Checkbutton
	tkinter.DISABLED
	tkinter.DOTBOX
	tkinter.DoubleVar
	tkinter.E
	tkinter.END
	tkinter.EW
	tkinter.EXCEPTION
	tkinter.EXTENDED
	tkinter.Entry
	tkinter.Event
	tkinter.EventType
	tkinter.FALSE
	tkinter.FIRST
	tkinter.FLAT
	tkinter.Frame
	tkinter.GROOVE
	tkinter.Grid
	tkinter.HIDDEN
	tkinter.HORIZONTAL
	tkinter.INSERT
	tkinter.INSIDE
	tkinter.Image
	tkinter.IntVar
	tkinter.LAST
	tkinter.LEFT
	tkinter.Label
	tkinter.LabelFrame
	tkinter.Listbox
	tkinter.MITER
	tkinter.MOVETO
	tkinter.MULTIPLE
	tkinter.Menu
	tkinter.Menubutton
	tkinter.Message
	tkinter.Misc
	tkinter.N
	tkinter.NE
	tkinter.NO
	tkinter.NONE
	tkinter.NORMAL
	tkinter.NS
	tkinter.NSEW
	tkinter.NUMERIC
	tkinter.NW
	tkinter.NoDefaultRoot
	tkinter.OFF
	tkinter.ON
	tkinter.OUTSIDE
	tkinter.OptionMenu
	tkinter.PAGES
	tkinter.PIESLICE
	tkinter.PROJECTING
	tkinter.Pack
	tkinter.PanedWindow
	tkinter.PhotoImage
	tkinter.Place
	tkinter.RADIOBUTTON
	tkinter.RAISED
	tkinter.READABLE
	tkinter.RIDGE
	tkinter.RIGHT
	tkinter.ROUND
	tkinter.Radiobutton
	tkinter.S
	tkinter.SCROLL
	tkinter.SE
	tkinter.SEL
	tkinter.SEL_FIRST
	tkinter.SEL_LAST
	tkinter.SEPARATOR
	tkinter.SINGLE
	tkinter.SOLID
	tkinter.SUNKEN
	tkinter.SW
	tkinter.Scale
	tkinter.Scrollbar
	tkinter.Spinbox
	tkinter.StringVar
	tkinter.TOP
	tkinter.TRUE
	tkinter.Tcl
	tkinter.TclError
	tkinter.TclVersion
	tkinter.Text
	tkinter.Tk
	tkinter.TkVersion
	tkinter.Toplevel
	tkinter.UNDERLINE
	tkinter.UNITS
	tkinter.VERTICAL
	tkinter.Variable
	tkinter.W
	tkinter.WORD
	tkinter.WRITABLE
	tkinter.Widget
	tkinter.Wm
	tkinter.X
	tkinter.XView
	tkinter.Y
	tkinter.YES
	tkinter.YView
	tkinter.__builtins__
	tkinter.__cached__
	tkinter.__doc__
	tkinter.__file__
	tkinter.__loader__
	tkinter.__name__
	tkinter.__package__
	tkinter.__path__
	tkinter.__spec__
	tkinter._cnfmerge
	tkinter._default_root
	tkinter._exit
	tkinter._flatten
	tkinter._join
	tkinter._magic_re
	tkinter._setit
	tkinter._space_re
	tkinter._splitdict
	tkinter._stringify
	tkinter._support_default_root
	tkinter._test
	tkinter._tkerror
	tkinter._tkinter
	tkinter._varnum
	tkinter.constants
	tkinter.enum
	tkinter.getboolean
	tkinter.getdouble
	tkinter.getint
	tkinter.image_names
	tkinter.image_types
	tkinter.mainloop
	tkinter.re
	tkinter.sys
	tkinter.wantobject




	